//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://it.cz.abb.com/SendMailWS/", ItemName="string")]
    internal class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/", ConfigurationName="MailServiceReference.ServiceSoap")]
    internal interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddr", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrResponse> SendMailToAddrAsync(MailServiceReference.SendMailToAddrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrA", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrAResponse> SendMailToAddrAAsync(MailServiceReference.SendMailToAddrARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrs", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsResponse> SendMailToAddrsAsync(MailServiceReference.SendMailToAddrsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrsA", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsAResponse> SendMailToAddrsAAsync(MailServiceReference.SendMailToAddrsARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrCC", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCResponse> SendMailToAddrCCAsync(MailServiceReference.SendMailToAddrCCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrCCA", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCAResponse> SendMailToAddrCCAAsync(MailServiceReference.SendMailToAddrCCARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrsCC", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCResponse> SendMailToAddrsCCAsync(MailServiceReference.SendMailToAddrsCCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrsCCA", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCAResponse> SendMailToAddrsCCAAsync(MailServiceReference.SendMailToAddrsCCARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrCCs", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCsResponse> SendMailToAddrCCsAsync(MailServiceReference.SendMailToAddrCCsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrCCsA", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCsAResponse> SendMailToAddrCCsAAsync(MailServiceReference.SendMailToAddrCCsARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrsCCs", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCsResponse> SendMailToAddrsCCsAsync(MailServiceReference.SendMailToAddrsCCsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.cz.abb.com/SendMailWS/SendMailToAddrsCCsA", ReplyAction="*")]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCsAResponse> SendMailToAddrsCCsAAsync(MailServiceReference.SendMailToAddrsCCsARequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddr", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrRequestBody Body;
        
        public SendMailToAddrRequest()
        {
        }
        
        public SendMailToAddrRequest(MailServiceReference.SendMailToAddrRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message;
        
        public SendMailToAddrRequestBody()
        {
        }
        
        public SendMailToAddrRequestBody(string AddrFROM, string AddrTO, string Subject, string Message)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.Subject = Subject;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrResponseBody Body;
        
        public SendMailToAddrResponse()
        {
        }
        
        public SendMailToAddrResponse(MailServiceReference.SendMailToAddrResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrResult;
        
        public SendMailToAddrResponseBody()
        {
        }
        
        public SendMailToAddrResponseBody(int SendMailToAddrResult)
        {
            this.SendMailToAddrResult = SendMailToAddrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrA", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrARequestBody Body;
        
        public SendMailToAddrARequest()
        {
        }
        
        public SendMailToAddrARequest(MailServiceReference.SendMailToAddrARequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrARequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] AttData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AttFileName;
        
        public SendMailToAddrARequestBody()
        {
        }
        
        public SendMailToAddrARequestBody(string AddrFROM, string AddrTO, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.Subject = Subject;
            this.Message = Message;
            this.AttData = AttData;
            this.AttFileName = AttFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrAResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrAResponseBody Body;
        
        public SendMailToAddrAResponse()
        {
        }
        
        public SendMailToAddrAResponse(MailServiceReference.SendMailToAddrAResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrAResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrAResult;
        
        public SendMailToAddrAResponseBody()
        {
        }
        
        public SendMailToAddrAResponseBody(int SendMailToAddrAResult)
        {
            this.SendMailToAddrAResult = SendMailToAddrAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrs", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsRequestBody Body;
        
        public SendMailToAddrsRequest()
        {
        }
        
        public SendMailToAddrsRequest(MailServiceReference.SendMailToAddrsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MailServiceReference.ArrayOfString AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message;
        
        public SendMailToAddrsRequestBody()
        {
        }
        
        public SendMailToAddrsRequestBody(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, string Subject, string Message)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.Subject = Subject;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsResponseBody Body;
        
        public SendMailToAddrsResponse()
        {
        }
        
        public SendMailToAddrsResponse(MailServiceReference.SendMailToAddrsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrsResult;
        
        public SendMailToAddrsResponseBody()
        {
        }
        
        public SendMailToAddrsResponseBody(int SendMailToAddrsResult)
        {
            this.SendMailToAddrsResult = SendMailToAddrsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsA", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsARequestBody Body;
        
        public SendMailToAddrsARequest()
        {
        }
        
        public SendMailToAddrsARequest(MailServiceReference.SendMailToAddrsARequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsARequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MailServiceReference.ArrayOfString AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] AttData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AttFileName;
        
        public SendMailToAddrsARequestBody()
        {
        }
        
        public SendMailToAddrsARequestBody(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.Subject = Subject;
            this.Message = Message;
            this.AttData = AttData;
            this.AttFileName = AttFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsAResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsAResponseBody Body;
        
        public SendMailToAddrsAResponse()
        {
        }
        
        public SendMailToAddrsAResponse(MailServiceReference.SendMailToAddrsAResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsAResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrsAResult;
        
        public SendMailToAddrsAResponseBody()
        {
        }
        
        public SendMailToAddrsAResponseBody(int SendMailToAddrsAResult)
        {
            this.SendMailToAddrsAResult = SendMailToAddrsAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrCCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrCC", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrCCRequestBody Body;
        
        public SendMailToAddrCCRequest()
        {
        }
        
        public SendMailToAddrCCRequest(MailServiceReference.SendMailToAddrCCRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrCCRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        public SendMailToAddrCCRequestBody()
        {
        }
        
        public SendMailToAddrCCRequestBody(string AddrFROM, string AddrTO, string CC, string Subject, string Message)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.CC = CC;
            this.Subject = Subject;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrCCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrCCResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrCCResponseBody Body;
        
        public SendMailToAddrCCResponse()
        {
        }
        
        public SendMailToAddrCCResponse(MailServiceReference.SendMailToAddrCCResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrCCResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrCCResult;
        
        public SendMailToAddrCCResponseBody()
        {
        }
        
        public SendMailToAddrCCResponseBody(int SendMailToAddrCCResult)
        {
            this.SendMailToAddrCCResult = SendMailToAddrCCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrCCARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrCCA", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrCCARequestBody Body;
        
        public SendMailToAddrCCARequest()
        {
        }
        
        public SendMailToAddrCCARequest(MailServiceReference.SendMailToAddrCCARequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrCCARequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] AttData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AttFileName;
        
        public SendMailToAddrCCARequestBody()
        {
        }
        
        public SendMailToAddrCCARequestBody(string AddrFROM, string AddrTO, string CC, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.CC = CC;
            this.Subject = Subject;
            this.Message = Message;
            this.AttData = AttData;
            this.AttFileName = AttFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrCCAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrCCAResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrCCAResponseBody Body;
        
        public SendMailToAddrCCAResponse()
        {
        }
        
        public SendMailToAddrCCAResponse(MailServiceReference.SendMailToAddrCCAResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrCCAResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrCCAResult;
        
        public SendMailToAddrCCAResponseBody()
        {
        }
        
        public SendMailToAddrCCAResponseBody(int SendMailToAddrCCAResult)
        {
            this.SendMailToAddrCCAResult = SendMailToAddrCCAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsCCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsCC", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsCCRequestBody Body;
        
        public SendMailToAddrsCCRequest()
        {
        }
        
        public SendMailToAddrsCCRequest(MailServiceReference.SendMailToAddrsCCRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsCCRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MailServiceReference.ArrayOfString AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        public SendMailToAddrsCCRequestBody()
        {
        }
        
        public SendMailToAddrsCCRequestBody(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, string CC, string Subject, string Message)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.CC = CC;
            this.Subject = Subject;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsCCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsCCResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsCCResponseBody Body;
        
        public SendMailToAddrsCCResponse()
        {
        }
        
        public SendMailToAddrsCCResponse(MailServiceReference.SendMailToAddrsCCResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsCCResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrsCCResult;
        
        public SendMailToAddrsCCResponseBody()
        {
        }
        
        public SendMailToAddrsCCResponseBody(int SendMailToAddrsCCResult)
        {
            this.SendMailToAddrsCCResult = SendMailToAddrsCCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsCCARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsCCA", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsCCARequestBody Body;
        
        public SendMailToAddrsCCARequest()
        {
        }
        
        public SendMailToAddrsCCARequest(MailServiceReference.SendMailToAddrsCCARequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsCCARequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MailServiceReference.ArrayOfString AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] AttData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AttFileName;
        
        public SendMailToAddrsCCARequestBody()
        {
        }
        
        public SendMailToAddrsCCARequestBody(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, string CC, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.CC = CC;
            this.Subject = Subject;
            this.Message = Message;
            this.AttData = AttData;
            this.AttFileName = AttFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsCCAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsCCAResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsCCAResponseBody Body;
        
        public SendMailToAddrsCCAResponse()
        {
        }
        
        public SendMailToAddrsCCAResponse(MailServiceReference.SendMailToAddrsCCAResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsCCAResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrsCCAResult;
        
        public SendMailToAddrsCCAResponseBody()
        {
        }
        
        public SendMailToAddrsCCAResponseBody(int SendMailToAddrsCCAResult)
        {
            this.SendMailToAddrsCCAResult = SendMailToAddrsCCAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrCCsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrCCs", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrCCsRequestBody Body;
        
        public SendMailToAddrCCsRequest()
        {
        }
        
        public SendMailToAddrCCsRequest(MailServiceReference.SendMailToAddrCCsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrCCsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MailServiceReference.ArrayOfString CC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        public SendMailToAddrCCsRequestBody()
        {
        }
        
        public SendMailToAddrCCsRequestBody(string AddrFROM, string AddrTO, MailServiceReference.ArrayOfString CC, string Subject, string Message)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.CC = CC;
            this.Subject = Subject;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrCCsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrCCsResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrCCsResponseBody Body;
        
        public SendMailToAddrCCsResponse()
        {
        }
        
        public SendMailToAddrCCsResponse(MailServiceReference.SendMailToAddrCCsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrCCsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrCCsResult;
        
        public SendMailToAddrCCsResponseBody()
        {
        }
        
        public SendMailToAddrCCsResponseBody(int SendMailToAddrCCsResult)
        {
            this.SendMailToAddrCCsResult = SendMailToAddrCCsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrCCsARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrCCsA", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrCCsARequestBody Body;
        
        public SendMailToAddrCCsARequest()
        {
        }
        
        public SendMailToAddrCCsARequest(MailServiceReference.SendMailToAddrCCsARequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrCCsARequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MailServiceReference.ArrayOfString CC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] AttData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AttFileName;
        
        public SendMailToAddrCCsARequestBody()
        {
        }
        
        public SendMailToAddrCCsARequestBody(string AddrFROM, string AddrTO, MailServiceReference.ArrayOfString CC, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.CC = CC;
            this.Subject = Subject;
            this.Message = Message;
            this.AttData = AttData;
            this.AttFileName = AttFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrCCsAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrCCsAResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrCCsAResponseBody Body;
        
        public SendMailToAddrCCsAResponse()
        {
        }
        
        public SendMailToAddrCCsAResponse(MailServiceReference.SendMailToAddrCCsAResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrCCsAResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrCCsAResult;
        
        public SendMailToAddrCCsAResponseBody()
        {
        }
        
        public SendMailToAddrCCsAResponseBody(int SendMailToAddrCCsAResult)
        {
            this.SendMailToAddrCCsAResult = SendMailToAddrCCsAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsCCsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsCCs", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsCCsRequestBody Body;
        
        public SendMailToAddrsCCsRequest()
        {
        }
        
        public SendMailToAddrsCCsRequest(MailServiceReference.SendMailToAddrsCCsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsCCsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MailServiceReference.ArrayOfString AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MailServiceReference.ArrayOfString CC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        public SendMailToAddrsCCsRequestBody()
        {
        }
        
        public SendMailToAddrsCCsRequestBody(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, MailServiceReference.ArrayOfString CC, string Subject, string Message)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.CC = CC;
            this.Subject = Subject;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsCCsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsCCsResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsCCsResponseBody Body;
        
        public SendMailToAddrsCCsResponse()
        {
        }
        
        public SendMailToAddrsCCsResponse(MailServiceReference.SendMailToAddrsCCsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsCCsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrsCCsResult;
        
        public SendMailToAddrsCCsResponseBody()
        {
        }
        
        public SendMailToAddrsCCsResponseBody(int SendMailToAddrsCCsResult)
        {
            this.SendMailToAddrsCCsResult = SendMailToAddrsCCsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsCCsARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsCCsA", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsCCsARequestBody Body;
        
        public SendMailToAddrsCCsARequest()
        {
        }
        
        public SendMailToAddrsCCsARequest(MailServiceReference.SendMailToAddrsCCsARequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsCCsARequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddrFROM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MailServiceReference.ArrayOfString AddrTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MailServiceReference.ArrayOfString CC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] AttData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AttFileName;
        
        public SendMailToAddrsCCsARequestBody()
        {
        }
        
        public SendMailToAddrsCCsARequestBody(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, MailServiceReference.ArrayOfString CC, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            this.AddrFROM = AddrFROM;
            this.AddrTO = AddrTO;
            this.CC = CC;
            this.Subject = Subject;
            this.Message = Message;
            this.AttData = AttData;
            this.AttFileName = AttFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class SendMailToAddrsCCsAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailToAddrsCCsAResponse", Namespace="http://it.cz.abb.com/SendMailWS/", Order=0)]
        public MailServiceReference.SendMailToAddrsCCsAResponseBody Body;
        
        public SendMailToAddrsCCsAResponse()
        {
        }
        
        public SendMailToAddrsCCsAResponse(MailServiceReference.SendMailToAddrsCCsAResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.cz.abb.com/SendMailWS/")]
    internal partial class SendMailToAddrsCCsAResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMailToAddrsCCsAResult;
        
        public SendMailToAddrsCCsAResponseBody()
        {
        }
        
        public SendMailToAddrsCCsAResponseBody(int SendMailToAddrsCCsAResult)
        {
            this.SendMailToAddrsCCsAResult = SendMailToAddrsCCsAResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal interface ServiceSoapChannel : MailServiceReference.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal partial class ServiceSoapClient : System.ServiceModel.ClientBase<MailServiceReference.ServiceSoap>, MailServiceReference.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrResponse> MailServiceReference.ServiceSoap.SendMailToAddrAsync(MailServiceReference.SendMailToAddrRequest request)
        {
            return base.Channel.SendMailToAddrAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrResponse> SendMailToAddrAsync(string AddrFROM, string AddrTO, string Subject, string Message)
        {
            MailServiceReference.SendMailToAddrRequest inValue = new MailServiceReference.SendMailToAddrRequest();
            inValue.Body = new MailServiceReference.SendMailToAddrRequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrAResponse> MailServiceReference.ServiceSoap.SendMailToAddrAAsync(MailServiceReference.SendMailToAddrARequest request)
        {
            return base.Channel.SendMailToAddrAAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrAResponse> SendMailToAddrAAsync(string AddrFROM, string AddrTO, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            MailServiceReference.SendMailToAddrARequest inValue = new MailServiceReference.SendMailToAddrARequest();
            inValue.Body = new MailServiceReference.SendMailToAddrARequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            inValue.Body.AttData = AttData;
            inValue.Body.AttFileName = AttFileName;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsResponse> MailServiceReference.ServiceSoap.SendMailToAddrsAsync(MailServiceReference.SendMailToAddrsRequest request)
        {
            return base.Channel.SendMailToAddrsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsResponse> SendMailToAddrsAsync(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, string Subject, string Message)
        {
            MailServiceReference.SendMailToAddrsRequest inValue = new MailServiceReference.SendMailToAddrsRequest();
            inValue.Body = new MailServiceReference.SendMailToAddrsRequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsAResponse> MailServiceReference.ServiceSoap.SendMailToAddrsAAsync(MailServiceReference.SendMailToAddrsARequest request)
        {
            return base.Channel.SendMailToAddrsAAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsAResponse> SendMailToAddrsAAsync(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            MailServiceReference.SendMailToAddrsARequest inValue = new MailServiceReference.SendMailToAddrsARequest();
            inValue.Body = new MailServiceReference.SendMailToAddrsARequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            inValue.Body.AttData = AttData;
            inValue.Body.AttFileName = AttFileName;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrsAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCResponse> MailServiceReference.ServiceSoap.SendMailToAddrCCAsync(MailServiceReference.SendMailToAddrCCRequest request)
        {
            return base.Channel.SendMailToAddrCCAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCResponse> SendMailToAddrCCAsync(string AddrFROM, string AddrTO, string CC, string Subject, string Message)
        {
            MailServiceReference.SendMailToAddrCCRequest inValue = new MailServiceReference.SendMailToAddrCCRequest();
            inValue.Body = new MailServiceReference.SendMailToAddrCCRequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.CC = CC;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrCCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCAResponse> MailServiceReference.ServiceSoap.SendMailToAddrCCAAsync(MailServiceReference.SendMailToAddrCCARequest request)
        {
            return base.Channel.SendMailToAddrCCAAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCAResponse> SendMailToAddrCCAAsync(string AddrFROM, string AddrTO, string CC, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            MailServiceReference.SendMailToAddrCCARequest inValue = new MailServiceReference.SendMailToAddrCCARequest();
            inValue.Body = new MailServiceReference.SendMailToAddrCCARequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.CC = CC;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            inValue.Body.AttData = AttData;
            inValue.Body.AttFileName = AttFileName;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrCCAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCResponse> MailServiceReference.ServiceSoap.SendMailToAddrsCCAsync(MailServiceReference.SendMailToAddrsCCRequest request)
        {
            return base.Channel.SendMailToAddrsCCAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCResponse> SendMailToAddrsCCAsync(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, string CC, string Subject, string Message)
        {
            MailServiceReference.SendMailToAddrsCCRequest inValue = new MailServiceReference.SendMailToAddrsCCRequest();
            inValue.Body = new MailServiceReference.SendMailToAddrsCCRequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.CC = CC;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrsCCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCAResponse> MailServiceReference.ServiceSoap.SendMailToAddrsCCAAsync(MailServiceReference.SendMailToAddrsCCARequest request)
        {
            return base.Channel.SendMailToAddrsCCAAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCAResponse> SendMailToAddrsCCAAsync(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, string CC, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            MailServiceReference.SendMailToAddrsCCARequest inValue = new MailServiceReference.SendMailToAddrsCCARequest();
            inValue.Body = new MailServiceReference.SendMailToAddrsCCARequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.CC = CC;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            inValue.Body.AttData = AttData;
            inValue.Body.AttFileName = AttFileName;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrsCCAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCsResponse> MailServiceReference.ServiceSoap.SendMailToAddrCCsAsync(MailServiceReference.SendMailToAddrCCsRequest request)
        {
            return base.Channel.SendMailToAddrCCsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCsResponse> SendMailToAddrCCsAsync(string AddrFROM, string AddrTO, MailServiceReference.ArrayOfString CC, string Subject, string Message)
        {
            MailServiceReference.SendMailToAddrCCsRequest inValue = new MailServiceReference.SendMailToAddrCCsRequest();
            inValue.Body = new MailServiceReference.SendMailToAddrCCsRequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.CC = CC;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrCCsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCsAResponse> MailServiceReference.ServiceSoap.SendMailToAddrCCsAAsync(MailServiceReference.SendMailToAddrCCsARequest request)
        {
            return base.Channel.SendMailToAddrCCsAAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrCCsAResponse> SendMailToAddrCCsAAsync(string AddrFROM, string AddrTO, MailServiceReference.ArrayOfString CC, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            MailServiceReference.SendMailToAddrCCsARequest inValue = new MailServiceReference.SendMailToAddrCCsARequest();
            inValue.Body = new MailServiceReference.SendMailToAddrCCsARequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.CC = CC;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            inValue.Body.AttData = AttData;
            inValue.Body.AttFileName = AttFileName;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrCCsAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCsResponse> MailServiceReference.ServiceSoap.SendMailToAddrsCCsAsync(MailServiceReference.SendMailToAddrsCCsRequest request)
        {
            return base.Channel.SendMailToAddrsCCsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCsResponse> SendMailToAddrsCCsAsync(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, MailServiceReference.ArrayOfString CC, string Subject, string Message)
        {
            MailServiceReference.SendMailToAddrsCCsRequest inValue = new MailServiceReference.SendMailToAddrsCCsRequest();
            inValue.Body = new MailServiceReference.SendMailToAddrsCCsRequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.CC = CC;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrsCCsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCsAResponse> MailServiceReference.ServiceSoap.SendMailToAddrsCCsAAsync(MailServiceReference.SendMailToAddrsCCsARequest request)
        {
            return base.Channel.SendMailToAddrsCCsAAsync(request);
        }
        
        public System.Threading.Tasks.Task<MailServiceReference.SendMailToAddrsCCsAResponse> SendMailToAddrsCCsAAsync(string AddrFROM, MailServiceReference.ArrayOfString AddrTO, MailServiceReference.ArrayOfString CC, string Subject, string Message, byte[] AttData, string AttFileName)
        {
            MailServiceReference.SendMailToAddrsCCsARequest inValue = new MailServiceReference.SendMailToAddrsCCsARequest();
            inValue.Body = new MailServiceReference.SendMailToAddrsCCsARequestBody();
            inValue.Body.AddrFROM = AddrFROM;
            inValue.Body.AddrTO = AddrTO;
            inValue.Body.CC = CC;
            inValue.Body.Subject = Subject;
            inValue.Body.Message = Message;
            inValue.Body.AttData = AttData;
            inValue.Body.AttFileName = AttFileName;
            return ((MailServiceReference.ServiceSoap)(this)).SendMailToAddrsCCsAAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://it.cz.abb.com/SendmailWS/MailSender.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://it.cz.abb.com/SendmailWS/MailSender.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
